# Site settings
title:
email:
author:
description:
url:

# Build settings
permalink: :title/
sass:
  sass_dir: css

 # Social icons
show_social_icons: true
github_username: robertdpowell
twitter_username: rdp81
linkedin_username: robertdpowell
