#-------------------------------
# General Site Settings

title: Rob Powell
subtitle: Thoughts.Ideas.More....
email: robertdpowell@gmail.com
author: Rob Powell

blurb:
  this comes from blurb



#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'www.google.com'}
- {icon: 'facebook', link: 'www.google.com'}
- {icon: 'linkedin', link: 'www.google.com'}
- {icon: 'youtube', link: 'www.google.com'}
- {icon: 'instagram', link: 'www.google.com'}

# can be 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'soundcloud'
